---
name: redis-warden
director_uuid: 28539132-6d43-4e1b-bf40-f2ce032ee9f8

jobs:
- instances: 3
  name: redis_dynomite
  persistent_disk: 4096
  networks:
  - name: redis
    static_ips: &ping_hosts
    - 10.244.0.2
    - 10.244.0.3
    - 10.244.0.4
  azs: [z1]
  resource_pool: small_z1
  templates:
  - name: redis
    release: redis

properties:
  redis: {}
releases:
- name: redis
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-100000
  max_in_flight: 50
  update_watch_time: 1000-100000
